In [1]:
import numpy as np

In [2]:
arr = np.arange(50).reshape((10,5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

# Transpose

In [4]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [5]:
np.dot(arr.T, arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [11]:
arr_3d = np.arange(8).reshape((2,2,2))
arr_3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [12]:
arr_3d.transpose((1,0,2))

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])

In [22]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [23]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

# Array: Common Functions 

In [29]:
my_arr = np.arange(11)*10
my_arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [30]:
np.sqrt(my_arr)

array([  0.        ,   3.16227766,   4.47213595,   5.47722558,
         6.32455532,   7.07106781,   7.74596669,   8.36660027,
         8.94427191,   9.48683298,  10.        ])

In [31]:
np.exp(my_arr)

array([  1.00000000e+00,   2.20264658e+04,   4.85165195e+08,
         1.06864746e+13,   2.35385267e+17,   5.18470553e+21,
         1.14200739e+26,   2.51543867e+30,   5.54062238e+34,
         1.22040329e+39,   2.68811714e+43])

In [33]:
A = np.random.randn(10) #Create a random array from a std normal distriution
A

array([ 0.90253577,  0.29804034,  0.12850524, -1.30680191, -0.93122955,
        3.26645915, -0.99317112, -0.88218534,  0.32452196,  2.12125391])

In [34]:
B = np.random.randn(10)
B

array([ 0.13091555,  1.2172538 , -0.01784973, -0.67220147,  0.95602427,
        0.22070529, -1.16429528,  1.02434261,  0.88684531, -2.70120227])

Binary Functions

In [35]:
# Addition 
np.add(A, B) 

array([ 1.03345132,  1.51529414,  0.1106555 , -1.97900338,  0.02479472,
        3.48716443, -2.15746641,  0.14215727,  1.21136727, -0.57994836])

In [36]:
# Find the maximum of two arrays 
np.maximum(A, B)

array([ 0.90253577,  1.2172538 ,  0.12850524, -0.67220147,  0.95602427,
        3.26645915, -0.99317112,  1.02434261,  0.88684531,  2.12125391])

In [37]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser

In [39]:
# Open the imported webbrower
webbrowser.open(website)

True